---
title: "ESM 244 Lab Week 2"
author: "Lory Salazar"
date: "1/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# For PCA:
library(ggfortify)

#For ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% # to select a column ending with "_mm"
  drop_na() %>% # in parenthesis can include specific variables to drop for instead of dropping all NAs
  scale() %>% # to scale the data 
  prcomp() # to run the PCA

penguin_pca$rotation

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm")) # we created this subset to have a subset of the data without the NAs for the variables we're interested in, but still including the other variables which we might want to use in our plot

# autoplot will assume that we want a biplot for the PCA
autoplot(penguin_pca,
         data = penguin_complete,
         colour = "species",
         loadings = TRUE,
         loadings.label = TRUE) +
  theme_minimal()
```


## Part 2: ggplot2 customization & reading in different file types

#### Read in an .xlsx file & do some wrangling

```{r}
fish_noaa <- read_excel(here("data","foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>%# mutating columns across whatever columns are a character class, to lowercase
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% # removes the last four characters from the values in that column; could also make a new column by saying nmfs_new instead of the same name
  filter(confidentiality == "public")
```

Make a customized graph:

```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds)) +
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()

fish_plot

ggplotly(fish_plot)

### Use gghighlight to highlight certain series

ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) + # group will separate into series but w/o color coding
  geom_line(aes(color = nmfs_name)) + # bc we added gghighlight, this will only color the highlighted groups we selected and others will be greyed out
  theme_minimal() +
  gghighlight(max(pounds) > 1e8) # highlights series where "variable" is greater than the number specified 
```

#### Read in from a URL, `lubridate()`, `mutate()`, make a graph with months in logical order

```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv") %>% 
  clean_names()
```


```{r}
monroe_ts <- monroe_wt %>% 
  mutate(date = mdy(date)) %>% 
  mutate(record_month = month(date)) %>% 
  mutate(month_name = month.abb[record_month]) %>% # to return the abbreviation of the month names from the record_month column
  mutate(month_name = fct_reorder(month_name, record_month)) # reorder month_name based on the values of record_month; do this so that the months show up in correct order rather than the default, which is alphabetically

ggplot(data = monroe_ts, aes(month_name, y = total_k_wh)) +
  geom_jitter()
```

## Part 3: Compound figures with `patchwork`

```{r}
graph_a <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

graph_b <- ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species), show.legend = FALSE)

# Use | to put graphs side by side
# Use / to put graphs one over the other

graph_c <- (graph_a | graph_b) / fish_plot & theme_dark()

graph_c

# default saves the most recently created plot
ggsave(here("fig","graph_c_ls.png"), width = 5, height = 6)
```


